name: Autograding Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-go-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # или нужная тебе версия

      - name: Run go test
        run: |
          go test ./... -v -coverprofile=coverage.out

      - name: Upload coverage report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
